export enum ActionType {
    //BUDGET
    SOME_CASE = "SOME_CASE",

    //TO DO
    ADD_NEW_TODO = "ADD_NEW_TODO",
    DELETE_TODO = "DELETE_TODO",
    UPDATE_TODO = "UPDATE_TODO",
    CHECK_TODO = "CHECK_TODO",

    //CARACTERS
    GET_CARACTERS = "GET_CARACTERS",
    GET_CARACTERS_ERROR = "GET_CARACTERS_ERROR",
    GET_CARACTERS_PAGINATION = "GET_CARACTERS_PAGINATION",
    GET_CARACTERS_PAGINATION_ERROR = "GET_CARACTERS_PAGINATION_ERROR",
}